from unidecode import unidecode

class Bible:
    def getBooksName(self, i):
        booksName = [
            'Genesis',
            'Exodus',
            'Leviticus',
            'Numbers',
            'Deuteronomy',
            'Joshua',
            'Judges',
            'Ruth',
            '1 Samuel',
            '2 Samuel',
            '1 Kings',
            '2 Kings',
            '1 Chronicles',
            '2 Chronicles',
            'Ezra',
            'Nehemiah',
            'Esther',
            'Job',
            'Psalm',
            'Proverbs',
            'Ecclesiastes',
            'Song of Solomon',
            'Isaiah',
            'Jeremiah',
            'Lamentations',
            'Ezekiel',
            'Daniel',
            'Hosea',
            'Joel',
            'Amos',
            'Obadiah',
            'Jonah',
            'Micah',
            'Nahum',
            'Habakkuk',
            'Zephaniah',
            'Haggai',
            'Zechariah',
            'Malachi',
            'Matthew',
            'Mark',
            'Luke',
            'John',
            'Acts',
            'Romans',
            '1 Corinthians',
            '2 Corinthians',
            'Galatians',
            'Ephesians',
            'Philippians',
            'Colossians',
            '1 Thessalonians',
            '2 Thessalonians',
            '1 Timothy',
            '2 Timothy',
            'Titus',
            'Philemon',
            'Hebrews',
            'James',
            '1 Peter',
            '2 Peter',
            '1 John',
            '2 John',
            '3 John',
            'Jude',
            'Revelation'
        ]

        return booksName[i]

    def getBooksAbbreviation(self, i):
        booksAbbreviation = [
            "GEN",
            "EXO",
            "LEV",
            "NUM",
            "DEU",
            "JOS",
            "JDG",
            "RUT",
            "1SA",
            "2SA",
            "1KI",
            "2KI",
            "1CH",
            "2CH",
            "EZR",
            "NEH",
            "EST",
            "JOB",
            "PSA",
            "PRO",
            "ECC",
            "SNG",
            "ISA",
            "JER",
            "LAM",
            "EZK",
            "DAN",
            "HOS",
            "JOL",
            "AMO",
            "OBA",
            "JON",
            "MIC",
            "NAM",
            "HAB",
            "ZEP",
            "HAG",
            "ZEC",
            "MAL",
            "MAT",
            "MRK",
            "LUK",
            "JHN",
            "ACT",
            "ROM",
            "1CO",
            "2CO",
            "GAL",
            "EPH",
            "PHP",
            "COL",
            "1TH",
            "2TH",
            "1TI",
            "2TI",
            "TIT",
            "PHM",
            "HEB",
            "JAS",
            "1PE",
            "2PE",
            "1JN",
            "2JN",
            "3JN",
            "JUD",
            "REV",
        ]

        return booksAbbreviation[i]

    def getBooksPtBRName(self, i):
        booksPtBrName = [
            "Gênesis",
            "Êxodo",
            "Levítico",
            "Números",
            "Deuteronômio",
            "Josué",
            "Juízes",
            "Rute",
            "1 Samuel",
            "2 Samuel",
            "1 Reis",
            "2 Reis",
            "1 Crônicas",
            "2 Crônicas",
            "Esdras",
            "Neemias",
            "Ester",
            "Jób",
            "Salmos",
            "Provérbios",
            "Eclesiastes",
            "Cânticos",
            "Isaías",
            "Jeremias",
            "Lamentações",
            "Ezequiel",
            "Dn",
            "Oséias",
            "Joel",
            "Amós",
            "Obadias",
            "Jonas",
            "Miquéias",
            "Naum",
            "Habacuque",
            "Sofonias",
            "Ageu",
            "Zacarias",
            "Malaquias",
            "Mateus",
            "Marcos",
            "Lucas",
            "João",
            "Atos",
            "Romanos",
            "1 Coríntios",
            "2 Coríntios",
            "Gálatas",
            "Efésios",
            "Filipenses",
            "Colossenses",
            "1 Tessalonicenses",
            "2 Tessalonicenses",
            "1 Timóteo",
            "2 Timóteo",
            "Tito",
            "Filemom",
            "Hebreus",
            "Tiago",
            "1 Pedro",
            "2 Pedro",
            "1 João",
            "2 João",
            "3 João",
            "Judas",
            "Apocalipse",
        ]

        return unidecode(booksPtBrName[i]).lower().replace(" ", "")
    
    def getbooksChapterNumber(self, i):
        booksChapterNumber = [
            "50",
            "40",
            "27",
            "36",
            "34",
            "24",
            "21",
            "4",
            "31",
            "24",
            "22",
            "25",
            "29",
            "36",
            "10",
            "13",
            "10",
            "42",
            "150",
            "31",
            "12",
            "8",
            "66",
            "52",
            "5",
            "48",
            "12",
            "14",
            "3",
            "9",
            "1",
            "4",
            "7",
            "3",
            "3",
            "3",
            "2",
            "14",
            "4",
            "28",
            "16",
            "24",
            "21",
            "26",
            "16",
            "16",
            "13",
            "6",
            "6",
            "4",
            "4",
            "5",
            "3",
            "6",
            "4",
            "3",
            "1",
            "13",
            "5",
            "5",
            "3",
            "5",
            "1",
            "1",
            "1",
            "22"
        ]

        return booksChapterNumber[i]